/**
 * Reports screen — consumes the existing PDF report generation endpoint.
 * Generates reports from backend data; no fake local reports.
 */
import React, { useState, useCallback } from 'react';
import { ScrollView, View, Text, TouchableOpacity, StyleSheet, Alert, RefreshControl } from 'react-native';
import { api } from '../../api/client';
import { COLORS, FONT_SIZE, RADIUS, SPACING } from '../../theme/colors';
import { SectionHeader, LoadingState } from '../../components';
import { ProvenanceBadge } from '../../components/ProvenanceBadge';

const REPORT_TYPES = [
  { id: 'daily_safety', title: 'Daily Safety & Operations', description: 'Mine-wide daily safety summary' },
  { id: 'incident_report', title: 'Critical Incident', description: 'Emergency incident documentation' },
  { id: 'panel_risk', title: 'Panel Risk Assessment', description: 'Per-panel subsidence risk analysis' },
  { id: 'sensor_health', title: 'Sensor Network Health', description: 'Node health and connectivity status' },
  { id: 'evacuation_report', title: 'Evacuation & Emergency', description: 'Evacuation event record' },
];

export function ReportsScreen() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [recentReports, setRecentReports] = useState<{ type: string; at: Date; success: boolean }[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetch = useCallback(async () => {
    try { await api.getHealth(); } catch { /* offline */ }
    finally { setLoading(false); setRefreshing(false); }
  }, []);

  React.useEffect(() => { fetch(); }, [fetch]);

  const generateReport = useCallback(async (reportType: string) => {
    setGenerating(reportType);
    try {
      const overview = await api.getDashboardOverview();
      const risk = overview.risk_intelligence;
      // Consume the existing PDF generation endpoint
      // POST /api/reports/generate returns application/pdf
      // The mobile app triggers the generation and receives the PDF bytes
      const success = await api.generateReport({
        report_type: reportType,
        data: {
          risk_level: risk.risk_level,
          risk_score: risk.current_risk_score,
          generated_by: 'TerraMesh Mobile',
          period: 'Current session',
          summary: `Risk: ${risk.risk_level} (${risk.current_risk_score}/100). ${risk.prediction}`,
          zones: [],
          exceptions: [],
        },
      });
      setRecentReports(prev => [{ type: reportType, at: new Date(), success }, ...prev].slice(0, 5));
      if (success) {
        Alert.alert('Report Generated', `${reportType} has been generated successfully.`);
      } else {
        Alert.alert('Report Failed', 'Report generation failed. Check connection.');
      }
    } catch (e) {
      Alert.alert('Error', 'Unable to generate report. Please check your connection and try again.');
      setRecentReports(prev => [{ type: reportType, at: new Date(), success: false }, ...prev].slice(0, 5));
    } finally { setGenerating(null); }
  }, []);

  if (loading) return <LoadingState label="Loading reports..." />;

  return (
    <ScrollView
      style={st.root}
      contentContainerStyle={st.content}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); fetch(); }} tintColor={COLORS.ACCENT} />}
    >
      <SectionHeader title="GENERATE REPORT" />
      {REPORT_TYPES.map(report => (
        <TouchableOpacity
          key={report.id}
          style={st.card}
          onPress={() => generateReport(report.id)}
          disabled={generating !== null}
          accessibilityLabel={`Generate ${report.title} report`}
        >
          <View style={st.row}>
            <View style={{ flex: 1 }}>
              <Text style={st.title}>{report.title}</Text>
              <Text style={st.desc}>{report.description}</Text>
            </View>
            <Text style={[st.generate, generating === report.id && { color: COLORS.WARNING }]}>
              {generating === report.id ? '...' : 'Generate →'}
            </Text>
          </View>
        </TouchableOpacity>
      ))}

      <View style={st.noteCard}>
        <Text style={st.noteText}>
          Reports are generated by the backend (fpdf2). They are NOT digitally
          signed. Data provenance is included in each report per the
          platform's provenance policy.
        </Text>
        <ProvenanceBadge label="MODEL OUTPUT" />
      </View>

      {recentReports.length > 0 && (
        <>
          <SectionHeader title="RECENT GENERATIONS" />
          {recentReports.map((r, i) => (
            <View key={i} style={st.recentCard}>
              <Text style={st.recentType}>{r.type}</Text>
              <Text style={st.recentTime}>{r.at.toLocaleString()}</Text>
              <Text style={[st.recentStatus, { color: r.success ? COLORS.SAFE : COLORS.CRITICAL }]}>
                {r.success ? '✓ Generated' : '✗ Failed'}
              </Text>
            </View>
          ))}
        </>
      )}
    </ScrollView>
  );
}

const st = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.BG },
  content: { padding: SPACING.LG },
  card: {
    backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.MD,
    borderWidth: 1, borderColor: COLORS.BORDER,
    padding: SPACING.LG, marginBottom: SPACING.SM,
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  title: { fontSize: FONT_SIZE.SMALL, fontWeight: '600', color: COLORS.TEXT_PRIMARY, marginBottom: 2 },
  desc: { fontSize: FONT_SIZE.CAPTION, color: COLORS.TEXT_MUTED },
  generate: { fontSize: FONT_SIZE.SMALL, fontWeight: '700', color: COLORS.ACCENT },
  noteCard: {
    backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.MD,
    borderWidth: 1, borderColor: COLORS.BORDER,
    padding: SPACING.LG, marginTop: SPACING.SM,
  },
  noteText: { fontSize: FONT_SIZE.CAPTION, color: COLORS.TEXT_MUTED, marginBottom: SPACING.SM },
  recentCard: {
    backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.SM,
    borderWidth: 1, borderColor: COLORS.BORDER,
    padding: SPACING.MD, marginBottom: 4,
    flexDirection: 'row', alignItems: 'center',
  },
  recentType: { flex: 1, fontSize: FONT_SIZE.CAPTION, fontWeight: '600', color: COLORS.TEXT_PRIMARY },
  recentTime: { fontSize: FONT_SIZE.CAPTION, color: COLORS.TEXT_MUTED, marginRight: 8 },
  recentStatus: { fontSize: FONT_SIZE.CAPTION, fontWeight: '700' },
});
