"""Initial schema — full TerraMesh MineGuard schema (PostgreSQL-safe).

Regenerated 2026-09-23. The previous revision of this migration was
autogenerated against a live SQLite-era database and was NOT safe to run on a
fresh PostgreSQL instance (it ALTERed `broadcast_history` before creating
it). This revision creates the complete schema from scratch and runs cleanly
on both PostgreSQL and SQLite (no dialect-specific statements).

PostGIS geometry columns, the TimescaleDB hypertable and its policies are
added by the follow-up migration `f3c9d2e7a4b1` which degrades gracefully
when those extensions are unavailable.

Revision ID: da6b437f9b5b
Revises:
Create Date: 2026-09-23 14:59:44.186738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6b437f9b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the complete MineGuard schema."""
    # ── Authentication / users ─────────────────────────────────────────────
    op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # ── Audit trail (append-only) ──────────────────────────────────────────
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('user_email', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('resource', sa.String(), nullable=True),
        sa.Column('previous_state', sa.Text(), nullable=True),
        sa.Column('new_state', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('session_id', sa.String(), nullable=True),
        sa.Column('detail', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)

    # ── Firebase push tokens ────────────────────────────────────────────────
    op.create_table('fcm_tokens',
        sa.Column('worker_id', sa.String(), nullable=False),
        sa.Column('token', sa.String(), nullable=True),
        sa.Column('platform', sa.String(), nullable=True),
        sa.Column('zone', sa.String(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_fcm_tokens_token'), 'fcm_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_fcm_tokens_worker_id'), 'fcm_tokens', ['worker_id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_zone'), 'fcm_tokens', ['zone'], unique=False)

    # ── Mines / panels ─────────────────────────────────────────────────────
    op.create_table('mines',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('location', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mines_id'), 'mines', ['id'], unique=False)

    op.create_table('panels',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('mine_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('workers_present', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panels_id'), 'panels', ['id'], unique=False)
    op.create_index(op.f('ix_panels_mine_id'), 'panels', ['mine_id'], unique=False)

    # ── Spatial entities (PostGIS geometry columns added in next migration) ─
    op.create_table('risk_zones',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('mine_id', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('subsidence_rate', sa.Float(), nullable=True),
        sa.Column('active_workers', sa.Integer(), nullable=True),
        sa.Column('active_sensors', sa.Integer(), nullable=True),
        sa.Column('polygon_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_zones_code'), 'risk_zones', ['code'], unique=False)
    op.create_index(op.f('ix_risk_zones_id'), 'risk_zones', ['id'], unique=False)
    op.create_index(op.f('ix_risk_zones_mine_id'), 'risk_zones', ['mine_id'], unique=False)

    op.create_table('evacuation_routes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('zone_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('eta_minutes', sa.Float(), nullable=True),
        sa.Column('waypoints_json', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evacuation_routes_id'), 'evacuation_routes', ['id'], unique=False)
    op.create_index(op.f('ix_evacuation_routes_zone_id'), 'evacuation_routes', ['zone_id'], unique=False)

    # ── Sensors / workers / alerts ─────────────────────────────────────────
    op.create_table('sensors',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('zone', sa.String(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('tilt', sa.Float(), nullable=True),
        sa.Column('displacement', sa.Float(), nullable=True),
        sa.Column('crack_width', sa.Float(), nullable=True),
        sa.Column('vibration', sa.String(), nullable=True),
        sa.Column('battery', sa.Integer(), nullable=True),
        sa.Column('lora_signal', sa.Integer(), nullable=True),
        sa.Column('ai_risk_score', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_name'), 'sensors', ['name'], unique=False)
    op.create_index(op.f('ix_sensors_zone'), 'sensors', ['zone'], unique=False)

    op.create_table('workers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('zone', sa.String(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('heart_rate', sa.Integer(), nullable=True),
        sa.Column('spo2', sa.Integer(), nullable=True),
        sa.Column('depth_m', sa.Integer(), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_code'), 'workers', ['code'], unique=True)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_zone'), 'workers', ['zone'], unique=False)

    op.create_table('alerts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('severity', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('zone', sa.String(), nullable=True),
        sa.Column('timestamp', sa.String(), nullable=True),
        sa.Column('acknowledged', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_zone'), 'alerts', ['zone'], unique=False)

    # ── Time-series telemetry ──────────────────────────────────────────────
    # Canonical hypertable-target store. Composite PK (node_id, ts) is
    # TimescaleDB-safe (every unique constraint includes the partitioning
    # column). Hypertable conversion happens in migration f3c9d2e7a4b1.
    op.create_table('telemetry',
        sa.Column('mine_id', sa.String(), nullable=False),
        sa.Column('node_id', sa.String(), nullable=False),
        sa.Column('ts', sa.DateTime(), nullable=False),
        sa.Column('tilt', sa.Float(), nullable=True),
        sa.Column('vibration', sa.Float(), nullable=True),
        sa.Column('displacement', sa.Float(), nullable=True),
        sa.Column('crack_width', sa.Float(), nullable=True),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Float(), nullable=True),
        sa.Column('battery', sa.Float(), nullable=True),
        sa.Column('signal_strength', sa.Float(), nullable=True),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column('warning_tier', sa.String(), nullable=True),
        sa.Column('provenance', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('node_id', 'ts')
    )
    op.create_index(op.f('ix_telemetry_mine_id'), 'telemetry', ['mine_id'], unique=False)
    op.create_index(op.f('ix_telemetry_node_id'), 'telemetry', ['node_id'], unique=False)
    op.create_index(op.f('ix_telemetry_ts'), 'telemetry', ['ts'], unique=False)
    op.create_index('ix_telemetry_node_ts', 'telemetry', ['node_id', 'ts'], unique=False)

    # Legacy telemetry log (kept for compatibility with older dev databases)
    op.create_table('telemetry_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sensor_id', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('tilt', sa.Float(), nullable=True),
        sa.Column('displacement', sa.Float(), nullable=True),
        sa.Column('crack_width', sa.Float(), nullable=True),
        sa.Column('vibration', sa.String(), nullable=True),
        sa.Column('ai_risk_score', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_sensor_id'), 'telemetry_logs', ['sensor_id'], unique=False)

    # ── Broadcast management ───────────────────────────────────────────────
    op.create_table('broadcasts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('archived_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.create_index(op.f('ix_broadcasts_name'), 'broadcasts', ['name'], unique=False)

    op.create_table('broadcast_recipients',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('broadcast_id', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_recipients_broadcast_id'), 'broadcast_recipients', ['broadcast_id'], unique=False)

    op.create_table('broadcast_channels',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('broadcast_id', sa.String(), nullable=True),
        sa.Column('sms_enabled', sa.Boolean(), nullable=True),
        sa.Column('email_enabled', sa.Boolean(), nullable=True),
        sa.Column('dashboard_enabled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_channels_broadcast_id'), 'broadcast_channels', ['broadcast_id'], unique=False)

    op.create_table('broadcast_history',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('broadcast_id', sa.String(), nullable=True),
        sa.Column('alert_id', sa.String(), nullable=True),
        sa.Column('sent_by', sa.String(), nullable=True),
        sa.Column('recipient_count', sa.Integer(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('alert_type', sa.String(), nullable=True),
        sa.Column('message_content', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_history_alert_id'), 'broadcast_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_broadcast_history_broadcast_id'), 'broadcast_history', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_broadcast_history_id'), 'broadcast_history', ['id'], unique=False)

    op.create_table('broadcast_delivery',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('history_id', sa.String(), nullable=True),
        sa.Column('recipient_id', sa.String(), nullable=True),
        sa.Column('channel', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('provider_message_id', sa.String(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.Column('failure_reason', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_delivery_history_id'), 'broadcast_delivery', ['history_id'], unique=False)
    op.create_index(op.f('ix_broadcast_delivery_recipient_id'), 'broadcast_delivery', ['recipient_id'], unique=False)


def downgrade() -> None:
    """Drop the complete MineGuard schema (reverse dependency order)."""
    op.drop_table('broadcast_delivery')
    op.drop_table('broadcast_history')
    op.drop_table('broadcast_channels')
    op.drop_table('broadcast_recipients')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_telemetry_logs_sensor_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index('ix_telemetry_node_ts', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_ts'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_node_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_mine_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('alerts')
    op.drop_table('workers')
    op.drop_table('sensors')
    op.drop_table('evacuation_routes')
    op.drop_table('risk_zones')
    op.drop_table('panels')
    op.drop_table('mines')
    op.drop_table('fcm_tokens')
    op.drop_table('audit_logs')
    op.drop_table('users')
