import os
import io
import logging
from datetime import datetime
from fpdf import FPDF

logger = logging.getLogger("terramesh.reports.pdf")

class PDFGenerator(FPDF):
    """
    Generates professional PDF safety reports using fpdf2.
    No system dependencies required.
    """
    
    def __init__(self, mine_name="TerraMesh AI Site", report_title="Safety Report"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.mine_name = mine_name
        self.report_title = report_title
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        
    def header(self):
        # Header banner
        self.set_fill_color(13, 21, 36) # Dark bg
        self.rect(0, 0, 210, 30, 'F')
        
        # TerraMesh Title
        self.set_text_color(56, 189, 248) # Cyan 400
        self.set_font("helvetica", "B", 18)
        self.set_xy(10, 10)
        self.cell(0, 10, "TerraMesh AI", ln=False, border=0)
        
        # Mine name
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "", 12)
        self.set_xy(10, 18)
        self.cell(0, 10, self.mine_name, ln=False, border=0)
        
        # Report Title
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 14)
        self.set_xy(0, 10)
        self.cell(200, 10, self.report_title, ln=False, border=0, align="R")
        
        # Date
        self.set_text_color(148, 163, 184) # Slate 400
        self.set_font("helvetica", "", 10)
        self.set_xy(0, 18)
        self.cell(200, 10, datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), ln=False, border=0, align="R")
        
        # Line break after header
        self.ln(25)

    def footer(self):
        # Position at 15 mm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()} | Generated by TerraMesh AI Risk Engine | CONFIDENTIAL", 0, 0, "C")

    def chapter_title(self, title):
        self.set_font("helvetica", "B", 14)
        self.set_text_color(15, 23, 42) # Slate 900
        self.cell(0, 10, title, 0, 1, "L")
        self.set_draw_color(203, 213, 225) # Slate 300
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def chapter_body(self, text):
        self.set_font("helvetica", "", 11)
        self.set_text_color(71, 85, 105) # Slate 600
        self.multi_cell(0, 6, text)
        self.ln(4)
        
    def add_key_value(self, key, value, alert=False):
        self.set_font("helvetica", "B", 11)
        self.set_text_color(71, 85, 105)
        self.cell(50, 6, f"{key}:", 0, 0, "L")
        
        self.set_font("helvetica", "B" if alert else "", 11)
        if alert:
            self.set_text_color(220, 38, 38) # Red 600
        else:
            self.set_text_color(15, 23, 42)
        self.cell(0, 6, str(value), 0, 1, "L")

    def build_report(self, data: dict) -> bytes:
        """
        Builds the PDF and returns it as a bytes buffer.
        """
        # --- Executive Summary ---
        self.chapter_title("1. Executive Summary")
        
        risk_level = data.get("risk_level", "NORMAL")
        risk_score = data.get("risk_score", 0)
        
        self.add_key_value("System Risk Status", risk_level, alert=risk_level in ["CRITICAL", "EVACUATE"])
        self.add_key_value("AI Risk Score", f"{risk_score}%")
        self.add_key_value("Generated By", data.get("generated_by", "System Operator"))
        self.add_key_value("Reporting Period", data.get("period", "Last 24 Hours"))
        
        self.ln(5)
        summary = data.get("summary", "All monitored sectors operating within nominal statutory safety thresholds.")
        self.chapter_body(summary)
        
        # --- Affected Zones ---
        if "zones" in data and data["zones"]:
            self.chapter_title("2. Sector Analysis")
            for z in data["zones"]:
                status = z.get("status", "NORMAL")
                self.set_font("helvetica", "B", 12)
                self.set_text_color(15, 23, 42)
                self.cell(0, 8, z.get("code", "Unknown Zone"), 0, 1, "L")
                
                self.add_key_value("Status", status, alert=status in ["CRITICAL", "WARNING"])
                self.add_key_value("Workers Present", z.get("workers", 0))
                self.add_key_value("Active Sensors", z.get("sensors", 0))
                self.ln(2)

        # --- Sensor Exceptions ---
        if "exceptions" in data and data["exceptions"]:
            self.chapter_title("3. Sensor Exceptions (DANGER / CRITICAL)")
            self.set_font("helvetica", "B", 10)
            self.set_fill_color(241, 245, 249) # Slate 100
            self.cell(40, 8, "Sensor ID", border=1, fill=True)
            self.cell(50, 8, "Type", border=1, fill=True)
            self.cell(40, 8, "Value", border=1, fill=True)
            self.cell(60, 8, "Provenance", border=1, fill=True)
            self.ln()
            
            self.set_font("helvetica", "", 10)
            for ex in data["exceptions"]:
                self.cell(40, 8, str(ex.get("id", "")), border=1)
                self.cell(50, 8, str(ex.get("type", "")), border=1)
                self.cell(40, 8, str(ex.get("value", "")), border=1)
                
                # Unlabeled rows are NOT assumed measured — that would be the
                # strongest claim. Honest default: UNLABELED.
                prov = str(ex.get("provenance", "UNLABELED"))
                self.cell(60, 8, prov, border=1)
                self.ln()
                
            self.ln(5)
            
        # --- Data Provenance Statement ---
        self.chapter_title("4. Data Provenance & Compliance")
        prov_text = (
            "This report is generated by the TerraMesh AI early-warning system. "
            "Data labeled as 'MEASURED' represents raw physical sensor readings. "
            "Data labeled as 'MODEL OUTPUT' represents AI-inferred states or Kalman-filtered data. "
            "Data labeled as 'SIMULATED' is synthetic data generated for training or testing purposes. "
            "This report is for internal safety monitoring and does not replace engineering manual audits."
        )
        self.chapter_body(prov_text)
        
        # Return bytes
        return self.output(dest='S')
